
SET @tableExists = SELECT count(*) FROM INFORMATION_SCHEMA.TABLES
                     WHERE TABLE_NAME='ACCOUNT' AND TABLE_SCHEMA='PUBLIC';

CREATE TABLE IF NOT EXISTS ACCOUNT (ID varchar(255) PRIMARY KEY, BALANCE DECIMAL, CURRENCY varchar(255) );

INSERT INTO ACCOUNT SELECT '12345678', 1000000, 'HKD' WHERE NOT @tableExists;
INSERT INTO ACCOUNT SELECT '88888888', 1000000, 'HKD' WHERE NOT @tableExists;
